/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistemaVendas;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStream;
import javax.swing.JDesktopPane;
import javax.swing.JInternalFrame;
import javax.swing.JOptionPane;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;
import org.jdom2.output.Format;
import org.jdom2.output.XMLOutputter;

/**
 *
 * @author BRUNO
 */
public class CadastroTipo extends javax.swing.JInternalFrame {

    /**
     * Creates new form CadastroTipo
     */
    JDesktopPane novaTela;
    CadastroProduto pegarTelaProduto;
    public CadastroTipo(JDesktopPane tela,CadastroProduto telaCadProd) {
        novaTela = tela;
        pegarTelaProduto = telaCadProd;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNovoTipoProduto = new javax.swing.JLabel();
        txtNovoTipoProduto = new javax.swing.JTextField();
        btnCadastrarTipoProduto = new javax.swing.JButton();
        btnCancelarTipoProduto = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro Tipo de produto ");

        lblNovoTipoProduto.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblNovoTipoProduto.setText("Novo Tipo de Produto:");

        btnCadastrarTipoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        btnCadastrarTipoProduto.setText("Cadastrar");
        btnCadastrarTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarTipoProdutoActionPerformed(evt);
            }
        });

        btnCancelarTipoProduto.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/cancel.png"))); // NOI18N
        btnCancelarTipoProduto.setText("Cancelar");
        btnCancelarTipoProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarTipoProdutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblNovoTipoProduto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNovoTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(btnCadastrarTipoProduto)
                        .addGap(43, 43, 43)
                        .addComponent(btnCancelarTipoProduto)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNovoTipoProduto)
                    .addComponent(txtNovoTipoProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelarTipoProduto)
                    .addComponent(btnCadastrarTipoProduto))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        String novoTipo="";
        Document doc;
        Element root;
    private void btnCadastrarTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarTipoProdutoActionPerformed
        File diretorioBanco = new File("Bancos de Dados");
        File bancoTipoProduto = new File(diretorioBanco,"BDtipoProduto.xml");
        novoTipo = txtNovoTipoProduto.getText();
        
        if(!bancoTipoProduto.exists()){
            root = new Element("BancoTipoProduto");
            doc = new Document(root);
            Element tipo = new Element("tipo");
            tipo.setText("---Selecione o Tipo---");
            root.addContent(tipo);
        }
        try{
            if(bancoTipoProduto.exists()){
                SAXBuilder builder = new SAXBuilder();
                doc = builder.build(bancoTipoProduto);
                root = (Element) doc.getRootElement();
            }
        }catch(JDOMException | IOException e){}
       
        Element tipo = new Element("tipo");
        tipo.setText(novoTipo);
        root.addContent(tipo);
        
        try {
            XMLOutputter xout = new XMLOutputter(Format.getPrettyFormat());
            OutputStream out = new FileOutputStream(new File(diretorioBanco,"BDtipoProduto.xml")); 
            xout.output(doc , out);
            out.close();
        } catch (IOException e) {}
        txtNovoTipoProduto.setText("");
        JOptionPane.showMessageDialog(null,"Cadastro com sucesso!!!","Cadastro de Tipo",JOptionPane.INFORMATION_MESSAGE);
        pegarTelaProduto.atualizarComboBox();
    }//GEN-LAST:event_btnCadastrarTipoProdutoActionPerformed

    private void btnCancelarTipoProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarTipoProdutoActionPerformed
       this.dispose();
    }//GEN-LAST:event_btnCancelarTipoProdutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrarTipoProduto;
    private javax.swing.JButton btnCancelarTipoProduto;
    private javax.swing.JLabel lblNovoTipoProduto;
    private javax.swing.JTextField txtNovoTipoProduto;
    // End of variables declaration//GEN-END:variables
}
