/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package sistemaVendas;

import java.awt.Component;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import org.jdom2.Document;
import org.jdom2.Element;
import org.jdom2.JDOMException;
import org.jdom2.input.SAXBuilder;

/**
 *
 * @author BRUNO
 */
public class NotaFiscal extends javax.swing.JInternalFrame {

    /**
     * Creates new form NotaFiscal
     */
    Relatorios relatorio;
    String numNota="";
    public NotaFiscal(String idNota, Relatorios x) {
        initComponents();
        tabProdutosRelatorio.setModel(model10);
        model10.setNumRows(0);
        tabProdutosRelatorio.setDefaultRenderer(Object.class, new CellRenderer());
        relatorio = x;
        numNota = idNota;
        carregarNota(numNota);
    }
    
    public NotaFiscal(String notaDaVenda){
        initComponents();
        tabProdutosRelatorio.setModel(model10);
        model10.setNumRows(0);
        tabProdutosRelatorio.setDefaultRenderer(Object.class, new CellRenderer());
        btnAnterior.setVisible(false);
        btnProximo.setVisible(false);
        carregarNota(notaDaVenda);
        
    }
    
    File diretorio = new File("Bancos de Dados");
    File bancoCliente = new File(diretorio,"BancoCliente.xml");
    File bancoNotas = new File(diretorio,"BancoNotas.xml");
    Document doc;
    Element root;
    
    public void carregarNota(String numeroNota){
        model10.setNumRows(0);
        try{
            SAXBuilder builder = new SAXBuilder();
            doc=builder.build(bancoNotas);
            root=(Element)doc.getRootElement();
            List<Element> notas = root.getChildren();
            for(int i=0;i<notas.size();i++){
                Element nota = notas.get(i);
                if(nota.getAttributeValue("Numeracao").equals(numeroNota)){
                    lblNumNota.setText("Número da Nota: "+nota.getAttributeValue("Numeracao"));
                    lblData.setText("Data: "+nota.getAttributeValue("Data"));
                    lblNomeCliente.setText("Nome: "+nota.getChild("Cliente").getChildText("Nome"));
                    lblTelefone.setText("Telefone: "+nota.getChild("Cliente").getChildText("Telefone"));
                    lblCpf.setText("CPF: "+nota.getChild("Cliente").getChildText("CPF"));
                    if(nota.getChild("Pagamento").getChildText("ModoPagamento").equals("Á Vista")){
                        lblModoPagamento.setText("Modo de Pagamento: Á Vista (10% de Desconto)");
                    }
                    else if(nota.getChild("Pagamento").getChildText("ModoPagamento").equals("Débito")){
                        lblModoPagamento.setText("Modo de Pagamento: Débito (5% de Desconto)");
                    }
                    else if(nota.getChild("Pagamento").getChildText("ModoPagamento").contains("Crédito")){
                        lblModoPagamento.setText("Modo de Pagamento: "+nota.getChild("Pagamento").getChildText("ModoPagamento"));
                    }
                    lblSubTotal.setText("Sub Total: R$ "+nota.getChild("Pagamento").getChildText("ValorTotalNota"));
                    lblTotalCompra.setText("Total da Compra: R$ "+nota.getChild("Pagamento").getChildText("ValorTotal"));
                    String dados[] = new String[4];
                    List<Element> produtos = nota.getChild("Produto").getChildren();
                    for(int j=0;j<produtos.size();j++){
                        Element item = produtos.get(j);
                        dados[0] = item.getText();
                        dados[1] = item.getAttributeValue("PrecoUnitario");
                        dados[2] = item.getAttributeValue("Quantidade");
                        dados[3] = item.getAttributeValue("PrecoTotal");
                        
                       model10.addRow(new Object[]{dados[0], dados[1], dados[2], dados[3]});
                    }
                }
            }
        }catch(JDOMException | IOException e){}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlInfoNota = new javax.swing.JPanel();
        lblNumNota = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        pnlInfoCliente = new javax.swing.JPanel();
        lblNomeCliente = new javax.swing.JLabel();
        lblTelefone = new javax.swing.JLabel();
        lblCpf = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        pnlCompra = new javax.swing.JPanel();
        lblModoPagamento = new javax.swing.JLabel();
        lblTotalCompra = new javax.swing.JLabel();
        lblSubTotal = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabProdutosRelatorio = new javax.swing.JTable();
        btnOk = new javax.swing.JButton();
        btnAnterior = new javax.swing.JButton();
        btnProximo = new javax.swing.JButton();

        setClosable(true);
        setTitle("Notal Fiscal");

        pnlInfoNota.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Info Nota Fiscal", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        pnlInfoNota.setMaximumSize(new java.awt.Dimension(409, 47));

        lblNumNota.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNumNota.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNumNota.setText("Número da Nota:");

        lblData.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblData.setText("Data:");

        javax.swing.GroupLayout pnlInfoNotaLayout = new javax.swing.GroupLayout(pnlInfoNota);
        pnlInfoNota.setLayout(pnlInfoNotaLayout);
        pnlInfoNotaLayout.setHorizontalGroup(
            pnlInfoNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoNotaLayout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(lblNumNota)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblData)
                .addGap(160, 160, 160))
        );
        pnlInfoNotaLayout.setVerticalGroup(
            pnlInfoNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoNotaLayout.createSequentialGroup()
                .addGroup(pnlInfoNotaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNumNota)
                    .addComponent(lblData))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pnlInfoCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Info Cliente", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 12))); // NOI18N
        pnlInfoCliente.setMaximumSize(new java.awt.Dimension(454, 58));

        lblNomeCliente.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblNomeCliente.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNomeCliente.setText("Nome:");

        lblTelefone.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblTelefone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTelefone.setText("Telefone:");

        lblCpf.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblCpf.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCpf.setText("CPF:");

        javax.swing.GroupLayout pnlInfoClienteLayout = new javax.swing.GroupLayout(pnlInfoCliente);
        pnlInfoCliente.setLayout(pnlInfoClienteLayout);
        pnlInfoClienteLayout.setHorizontalGroup(
            pnlInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoClienteLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblNomeCliente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblTelefone)
                .addGap(166, 166, 166)
                .addComponent(lblCpf)
                .addGap(126, 126, 126))
        );
        pnlInfoClienteLayout.setVerticalGroup(
            pnlInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoClienteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefone)
                    .addComponent(lblNomeCliente)
                    .addComponent(lblCpf))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnlCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true), "Compra", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 10))); // NOI18N
        pnlCompra.setMaximumSize(new java.awt.Dimension(717, 328));

        lblModoPagamento.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblModoPagamento.setText("Modo de Pagamanto:");

        lblTotalCompra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalCompra.setText("Total da Compra: R$");

        lblSubTotal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblSubTotal.setText("Sub Total: R$");

        tabProdutosRelatorio.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tabProdutosRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabProdutosRelatorio.setEnabled(false);
        tabProdutosRelatorio.setShowHorizontalLines(false);
        tabProdutosRelatorio.setShowVerticalLines(false);
        jScrollPane2.setViewportView(tabProdutosRelatorio);

        javax.swing.GroupLayout pnlCompraLayout = new javax.swing.GroupLayout(pnlCompra);
        pnlCompra.setLayout(pnlCompraLayout);
        pnlCompraLayout.setHorizontalGroup(
            pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCompraLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 687, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(pnlCompraLayout.createSequentialGroup()
                        .addComponent(lblModoPagamento)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblTotalCompra)
                            .addComponent(lblSubTotal))
                        .addGap(105, 105, 105))))
        );
        pnlCompraLayout.setVerticalGroup(
            pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblModoPagamento)
                    .addComponent(lblSubTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addComponent(lblTotalCompra)
                .addContainerGap())
        );

        btnOk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/ok.png"))); // NOI18N
        btnOk.setText("OK");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnAnterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/preview.jpg"))); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnProximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/next.jpg"))); // NOI18N
        btnProximo.setText("Próximo");
        btnProximo.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        btnProximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(pnlCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInfoNota, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnlInfoCliente, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk)
                        .addGap(243, 243, 243)
                        .addComponent(btnProximo)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlInfoNota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlInfoCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnAnterior)
                            .addComponent(btnProximo))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnOk)
                        .addGap(22, 22, 22))))
        );

        setBounds(0, 0, 805, 557);
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOkActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        String idNota = lblNumNota.getText().replace("Número da Nota: ", "");
        String anteriorNota = relatorio.NumeroDaNota_Referente_A_Tabela(idNota,"anterior");
        carregarNota(anteriorNota);
    }//GEN-LAST:event_btnAnteriorActionPerformed

    private void btnProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProximoActionPerformed
        String idNota = lblNumNota.getText().replace("Número da Nota: ", "");
        String proxNota = relatorio.NumeroDaNota_Referente_A_Tabela(idNota,"prox");
        carregarNota(proxNota);
    }//GEN-LAST:event_btnProximoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnProximo;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblCpf;
    private javax.swing.JLabel lblData;
    private javax.swing.JLabel lblModoPagamento;
    private javax.swing.JLabel lblNomeCliente;
    private javax.swing.JLabel lblNumNota;
    private javax.swing.JLabel lblSubTotal;
    private javax.swing.JLabel lblTelefone;
    private javax.swing.JLabel lblTotalCompra;
    private javax.swing.JPanel pnlCompra;
    private javax.swing.JPanel pnlInfoCliente;
    private javax.swing.JPanel pnlInfoNota;
    private javax.swing.JTable tabProdutosRelatorio;
    // End of variables declaration//GEN-END:variables

    private DefaultTableModel model10 = new DefaultTableModel(  
            new Object[] []{ },  
            new String[] {"Produto","Preço Unitário","Quantidade","Total"}  
         ) {  
  
            public boolean isCellEditable(int row, int col) {  
                    return false;  
            }  
         };
    //Edição da tabela
    public class CellRenderer extends DefaultTableCellRenderer {  
  
    public CellRenderer() {  
        super();  
    }  
  
    public Component getTableCellRendererComponent(JTable table, Object value,  
            boolean isSelected, boolean hasFocus, int row, int column) {  
        this.setHorizontalAlignment(CENTER); //alinha texto ao centro 
  
        return super.getTableCellRendererComponent(table, value, isSelected,  
                hasFocus, row, column);  
    }  
} 
}
